with-expecter: True
all: true
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
log-level: "info"
packages:
  github.com/steffakasid/trivy-scanner/internal:
    config:
      dir: "internal/mocks"
      recursive: True
